apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-pvc
  labels:   
    type: local-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     # Usando todo o recurso disponivel no PV
     storage: 5Mi
  selector:
    matchLabels:
     # informando qual PV será utilizado 
     type : local-pv 