apiVersion: v1
kind: Pod
metadata:
  name: aspnet-pod
spec:
  containers:
   - name: aspnet-container
     image: ewernet/pizzafrontend:latest
     ports:
      - containerPort: 80
        name: "frontend-mvc"
     volumeMounts:
        - mountPath: "/app/meuvolume"
          name: aspnet-storage
  volumes:
    - name: aspnet-storage
      persistentVolumeClaim:
        # informando qual PVC será utilizado
        claimName: aspnet-pvc
