apiVersion: v1
kind: PersistentVolume
metadata:
  name: aspnet-pv
  labels:
    type: local-pv
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy : Recycle 
  hostPath:
    path: "/app/meuvolume"
  storageClassName: manual