apiVersion: v1
kind: Pod
metadata:
  name: teste-pod
spec:
   containers:
    - name: teste-cont
      image: nginx
      volumeMounts:
      - name: mysecret
        mountPath: "/etc/mysecret"
        readOnly: true
   volumes:
    - name: mysecret
      secret:
       secretName: mysecret-gh8bgf47m5